### ISSUE TITLE
KG 이니시스 본인인증 관련 이슈

### ISSUE THREAD

**Issue by nohhyemin08** [portone-io/portone_flutter#103]
샘플코드의

 Navigator.pushReplacementNamed(
          context,
          '/result',
          arguments: result,
        );
를 사용하여 result 로 이동하려 하면 화면이 뜨지 않고 

E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): Failed to handle method call result
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): java.lang.IllegalStateException: navigationRequest calls must succeed
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at kr.iamport.iamport_webview_flutter.FlutterWebViewClient$OnNavigationRequestResult.error(FlutterWebViewClient.java:301)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:237)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:380)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:1003)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at android.os.Looper.loopOnce(Looper.java:186)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#plugins.flutter.io/imp_webview_0( 9503): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

해당 에러가 발생합니다. 

혹시 Navigator.pushReplacementNamed 말고 Get.to(() => const Result(), arguments: result) 를 사용하여 이동하여도 괜찮은지 궁금합니다.

**Comment by anymate98** [comment]
예제에서는 이미 Get을 사용해 돌아가는 방식을 시연하고 있습니다. 돌아가는 방법은 어떠한 것을 쓰셔도 무방할 듯 합니다.
